---

- name: Check for an existing backup directory
  stat:
    path: "{{ backup_dir }}"
  register: bdir

- name: Ensures the backup directory exists
  file:
    path: "{{ backup_dir }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0775
    state: directory
  when: not bdir.stat.exists or not bdir.stat.isdir
