---

- include: install_additional_packages.yml
  tags: packages

- include: setup_maintenance_page.yml

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: backup_media.yml
  tags:
    - never
    - deploy
    - backup
  when: run_backups

- name: Activate maintenance page
  command: mv {{ maintenance_dir }}/maintenance_off.html {{ maintenance_dir }}/maintenance_on.html

- include: setup_git_repo.yml
  tags: deploy

- include: setup_frontend_file_structure.yml
  tags: deploy

- include: setup_django_app.yml
  tags: deploy

- include: setup_supervisor.yml
  tags: supervisor

- include: set_file_permissions.yml
  tags: deploy

- name: Deactivate maintenance page
  command: mv {{ maintenance_dir }}/maintenance_on.html {{ maintenance_dir }}/maintenance_off.html

- include: run_django_preset_db.yml
  tags:
    - never
    - run_preset_db
  when: env != 'production'
