---

virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"

celery_user: "{{ application_name }}"
celery_group: webapps

celery_application_name: celery
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_worker_start_template_file: "{{ celery_application_name }}_worker_start.j2"
celery_beat_start_template_file: "{{ celery_application_name }}_beat_start.j2"

celery_log_dir: "{{ virtualenv_path }}/logs/celery"
celery_worker_stdout_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}_workder_stdout.log"
celery_worker_stderr_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}_workder_stderr.log"
celery_beat_stdout_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}_beat_stdout.log"
celery_beat_stderr_log_file: "{{ celery_log_dir }}/{{ celery_application_name }}_beat_stderr.log"
