---

- name: Checks whether the maintenance on page exists
  stat:
    path: "{{ maintenance_dir }}/maintenance_on.html"
  register: maintenance_on_result

- name: Checks whether the maintenance off page exists
  stat:
    path: "{{ maintenance_dir }}/maintenance_off.html"
  register: maintenance_off_result

- include: setup_maintenance_page.yml
  when: not maintenance_on_result.stat.exists and not maintenance_off_result.stat.exists

- name: Activate maintenance page
  command: mv {{ maintenance_dir }}/maintenance_off.html {{ maintenance_dir }}/maintenance_on.html
  tags:
    - deploy_back
    - deploy_front
  when: not maintenance_on_result.stat.exists
