---

- name: Check for an existing media backup directory
  stat:
    path: "{{ media_backup_dir }}"
  register: mediabdir

- name: Ensures the media backup directory exists
  file:
    path: "{{ media_backup_dir }}"
    owner: root
    group: root
    mode: 0775
    state: directory
  when: not mediabdir.stat.exists or not mediabdir.stat.isdir

- name: Check for an existing media directory
  stat:
    path: "{{ nginx_media_dir }}"
  register: mediadir

- name: Archive the media directory
  archive:
    path: "{{ nginx_media_dir }}"
    dest: "{{ media_backup_dir }}/{{ application_name }}-media-{{ ansible_date_time.epoch }}.tgz"
  when: mediadir.stat.exists

- name: Copy the media archive to the local machine
  fetch:
    src: "{{ media_backup_dir }}/{{ application_name }}-media-{{ ansible_date_time.epoch }}.tgz"
    dest: "{{ local_backup_dir }}/"
    flat: yes
  when: mediadir.stat.exists
