---

# The media folder is expected to live one directory up in /webapps/application_name/media
- name: Remove {{ project_path }} contents
  file:
    state: absent
    path: "{{ project_path }}/"

- name: Recreate {{ project_path }} directory
  file:
    state: directory
    path: "{{ project_path }}/"

- name: Move the django content to the project_path
  command: rsync -r {{ tmp_build.path }}/src/django/ {{ project_path }}/ --exclude test

- name: Copy the requirements folder
  command: cp -r {{ tmp_build.path }}/requirements {{ project_path }}/requirements

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run the Django syncdb command
  django_manage:
    command: syncdb
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ project_environment }}"
  when: run_django_syncdb is defined and run_django_syncdb
  tags:
    - django.syncdb

- name: Update db user to have superuser privilages
  become: true
  become_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   encrypted=yes
                   priv=ALL
                   role_attr_flags=SUPERUSER
                   state=present

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ project_environment }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags:
    - django.migrate

- name: Remove superuser privileges from db user
  become: true
  become_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   encrypted=yes
                   priv=ALL
                   role_attr_flags=NOSUPERUSER
                   state=present

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ project_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  notify: restart application
  tags:
    - django.collectstatic

- name: Ensure that the application file permissions are set properly
  file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  changed_when: false
