---

- name: Check for an existing frontend logdir
  stat:
    path: "{{ nginx_frontend_log_dir }}"
  register: log_dir

- name: Create the application log folder
  file: path={{ nginx_frontend_log_dir }}
        owner={{ nginx_user }}
        group={{ nginx_group }}
        mode=0774
        state=directory
  when: not log_dir.stat.exists or not log_dir.stat.isdir

- name: Check for an existing frontend access_log
  stat:
    path: "{{ nginx_frontend_access_log_file }}"
  register: access_log

- name: Check for an existing frontend error_log
  stat:
    path: "{{ nginx_frontend_error_log_file }}"
  register: error_log

- name: Create (or retain) the frontend access_log
  file:
    path: "{{ nginx_frontend_access_log_file }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0664
    state: '{{ "file" if  access_log.stat.exists else "touch" }}'

- name: Create (or retain) the frontend error_log
  file:
    path: "{{ nginx_frontend_error_log_file }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0664
    state: '{{ "file" if  error_log.stat.exists else "touch" }}'
