---
- name: Add main-contrib APT repositories
  apt_repository:
    repo: deb-src http://deb.debian.org/debian {{ ansible_distribution_release }} main
    state: present

- name: Add main security updates APT repositories
  apt_repository:
    repo: deb-src http://deb.debian.org/debian-security/ {{ ansible_distribution_release }}/updates main
    state: present

- name: Add main updates APT repositories
  apt_repository:
    repo: deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-updates main
    state: present
