---
- hosts: application
  become: true
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic
        state: directory
        mode: '0755'

    - name: copy init script
      copy:
        backup_server: init_repo.py
        application_server: /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic
        mode: '0644'

    - name: Copy backup recovery script
      copy:
        backup_server: recover_backup.py
        application_server: /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic
        mode: '0644'

    - name: Copy backup push script
      copy:
        backup_server: push.py
        application_server: /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic
        mode: '0644'

    - name: Copy backup recovery script
      copy:
        backup_server: recover_backup_db.py
        application_server: /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic
        mode: '0644'

    - name: Copy backup push script
      copy:
        backup_server: push_db.py
        application_server: /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic
        mode: '0644'

    - name: send key
      copy:
        backup_server: {{ key-placeholder }}
        application_server: /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic
        mode: '0400'

    - name: send key
      copy:
        backup_server: {{ key-placeholder }}
        application_server: /webapps/ejournal/VLE/VLE/tasks/beats/
        mode: '0400'

    - name: Init the repo
      script: init_repo.py
      args:
        executable: python3
      register: get_output
      become: yes

    - debug: var=get_output.stdout_lines

    - name: change premissions
      raw: sudo chmod -R 777 /webapps/ejournal/VLE/VLE/tasks/beats/backuplogic


- hosts: backup
  become: true
  tasks:
    - name: add python3 repo
      raw: sudo apt install -y python3

    - name: send key
      copy:
        backup_server: {{ key-placeholder }}
        application_server: /home/{{ user-placeholder }}
        mode: '0400'

    - name: copy pull script
      copy:
        backup_server: pull.py
        application_server: /home/{{ user-placeholder }}
        mode: '0644'

