# Generated by Django 2.1 on 2018-09-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='max_points',
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.IntegerField(default=10, verbose_name='points_possible'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.TextField(choices=[('t', 'text'), ('rt', 'rich text'), ('i', 'img'), ('p', 'pdf'), ('f', 'file'), ('v', 'vid'), ('u', 'url'), ('d', 'date')], default='t', max_length=4),
        ),
    ]
