# Generated by Django 2.1 on 2018-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0002_auto_20180920_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='max_points',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.IntegerField(default=10, verbose_name='points_possible'),
        ),
    ]
