# Generated by Django 2.1 on 2018-09-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0002_auto_20180926_1105'),
        ('VLE', '0002_auto_20180926_1822'),
    ]

    operations = [
    ]
