# Generated by Django 2.1 on 2018-10-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0004_UserFile_more_detailed_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VLE.Entry'),
        ),
    ]
