# Generated by Django 2.1.2 on 2018-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0004_userfile_more_detailed_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetnode',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
