# Generated by Django 2.1 on 2018-09-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0004_participation_role_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VLE.Content'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VLE.Node'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VLE.Entry'),
        ),
    ]
