# Generated by Django 2.1.2 on 2018-10-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0005_presetnode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_gdpr',
            field=models.DateTimeField(null=True),
        ),
    ]
