# Generated by Django 2.1.2 on 2018-10-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0006_assignment_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='published',
            new_name='is_published',
        ),
    ]
