# Generated by Django 2.1.2 on 2018-10-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0006_can_view_assignment_journals_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_standalone_registration', models.BooleanField(default=True)),
                ('name', models.TextField(default='eJournal')),
            ],
        ),
    ]
