# Generated by Django 2.1.2 on 2018-10-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0007_instance'),
        ('VLE', '0007_assignment_published'),
    ]

    operations = [
    ]
