# Generated by Django 2.1.2 on 2018-10-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0007_auto_20181016_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_view_unpublished',
            field=models.BooleanField(default=False),
        ),
    ]
