# Generated by Django 2.1.2 on 2018-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0007_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_unpublished_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
