# Generated by Django 2.1.2 on 2018-10-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0008_role_can_view_unpublished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='can_view_unpublished',
            new_name='can_view_unpublished_assignment',
        ),
    ]
