# Generated by Django 2.1.2 on 2018-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0008_assignment_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='options',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.TextField(choices=[('t', 'text'), ('rt', 'rich text'), ('i', 'img'), ('p', 'pdf'), ('f', 'file'), ('v', 'vid'), ('u', 'url'), ('d', 'date'), ('s', 'selection')], default='t', max_length=4),
        ),
    ]
