# Generated by Django 2.1.2 on 2018-10-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0009_add_selection_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
