# Generated by Django 2.1.2 on 2018-11-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0010_auto_20181027_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='vle_coupling',
            field=models.TextField(choices=[('Submission need to be send to VLE', 'entry_submission'), ('Submission is successfully recieved by VLE', 'entry_submitted'), ('Grade need to be send to VLE', 'grade_submission'), ('Everything is send to VLE', 'done')], default='Submission need to be send to VLE'),
        ),
    ]
