# Generated by Django 2.1.2 on 2019-01-26 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_user_preferences(apps, schema_editor):
    User = apps.get_model('VLE', 'User')
    UserPreferences = apps.get_model('VLE', 'UserPreferences')
    for user in User.objects.all():
        UserPreferences.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0012_auto_20181211_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_format_editor_tutorial', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            populate_user_preferences,
        ),
    ]
