# Generated by Django 2.1.2 on 2019-01-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_user_preferences(apps, schema_editor):
    User = apps.get_model('VLE', 'User')
    Preferences = apps.get_model('VLE', 'Preferences')
    for user in User.objects.all():
        Preferences.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0012_auto_20181211_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('show_format_editor_tutorial', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, primary_key=True)),
            ],
        ),
        migrations.RunPython(
            populate_user_preferences,
        ),
    ]
