# Generated by Django 2.1.2 on 2018-11-06 15:06

from django.db import migrations, models


def combine_names(apps, schema_editor):
    User = apps.get_model('VLE', 'User')
    for user in User.objects.all():
        user.full_name = '{} {}'.format(user.first_name, user.last_name)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0012_auto_20181211_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RunPython(combine_names),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=200, null=False),
        ),
    ]
