# Generated by Django 2.1.2 on 2019-02-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0013_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='bonus_points',
            field=models.FloatField(default=0),
        ),
    ]
