# Generated by Django 2.1.7 on 2019-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0015_user_feedback_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='upcoming_deadline_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
