# Generated by Django 2.1.7 on 2019-03-17 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_permission_for_teachers(apps, schema_editor):
    Role = apps.get_model('VLE', 'Role')
    Role.objects.filter(name='Teacher').update(can_edit_staff_comment=True)


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0016_preferences_upcoming_deadline_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_staff_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_permission_for_teachers,
        ),
    ]
