# Generated by Django 2.1.7 on 2019-03-06 11:16

from django.db import migrations, models


def group_to_groups(apps, schema_editor):
    Participation = apps.get_model('VLE', 'Participation')
    for participation in Participation.objects.filter(group__isnull=False):
        # If the name includes a ',', it is ment to be multiple groups.
        # We can simply just ignore those for now, as they then will update next time when the user logs in through LTI
        if ',' not in participation.group.name:
            participation.groups.set([participation.group])
            participation.save()
        else:
            participation.groups.set([])
            participation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0017_can_edit_staff_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='groups',
            field=models.ManyToManyField(default=None, to='VLE.Group'),
        ),
        migrations.RunPython(
            group_to_groups,
        ),
        migrations.RemoveField(
            model_name='participation',
            name='group',
        ),
    ]
