# Generated by Django 2.1.7 on 2019-03-15 20:22

from django.db import migrations, models
from django.db.models import F


def set_entry_lock_dates(apps, schema_editor):
    PresetNode = apps.get_model('VLE', 'PresetNode')
    PresetNode.objects.all().update(lock_date=F('due_date'))


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0018_multiple_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presetnode',
            old_name='deadline',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='presetnode',
            name='lock_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='presetnode',
            name='unlock_date',
            field=models.DateTimeField(null=True),
        ),
    ]
