# Generated by Django 2.1.7 on 2019-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0019_unlock_due_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='hide_version_alert',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
