# Generated by Django 2.1.7 on 2019-03-06 11:16

from django.conf import settings
from django.db import migrations, models


def update_unknown_profile_pic_url(apps, schema_editor):
    User = apps.get_model('VLE', 'User')
    for user in User.objects.all():
        if user.profile_picture == '/static/unknown-profile.png':
            user.profile_picture = settings.DEFAULT_PROFILE_PICTURE
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0020_preferences_hide_version_alert'),
    ]

    operations = [
        migrations.RunPython(
            update_unknown_profile_pic_url,
        ),
    ]
