# Generated by Django 2.1.7 on 2019-05-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_entry_grades(apps, schema_editor):
    Grade = apps.get_model('VLE', 'Grade')
    Entry = apps.get_model('VLE', 'Entry')
    for entry in Entry.objects.all():
        if entry.grade:
            Grade.objects.create(entry=entry, grade=entry.grade, published=entry.published, author=None)


def link_entry_grades(apps, schema_editor):
    Grade = apps.get_model('VLE', 'Grade')
    Entry = apps.get_model('VLE', 'Entry')
    for entry in Entry.objects.all():
        entry.grade = Grade.objects.filter(entry=entry).first()
        entry.save()


def set_permission_for_teachers(apps, schema_editor):
    Role = apps.get_model('VLE', 'Role')
    Role.objects.filter(name='Teacher').update(can_view_grade_history=True)


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0021_unknown_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='VLE.Entry')),
                ('grade', models.FloatField(editable=False, null=True)),
                ('published', models.BooleanField(default=False, editable=False)),
                ('creation_date', models.DateTimeField(editable=False)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            create_entry_grades,
        ),
        migrations.RemoveField(
            model_name='entry',
            name='published',
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_grade_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='VLE.Grade'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='vle_coupling',
            field=models.TextField(choices=[('Submission needs to be sent to VLE', 'entry_submission'), ('Submission is successfully received by VLE', 'entry_submitted'), ('Grade needs to be sent to VLE', 'grade_submission'), ('Everything is sent to VLE', 'done')], default='Submission needs to be sent to VLE'),
        ),
        migrations.RunPython(
            link_entry_grades,
        ),
        migrations.RunPython(
            set_permission_for_teachers,
        ),
    ]
