# Generated by Django 2.1.7 on 2019-08-07 14:28

import django.db.models.deletion
from django.db import migrations, models


def update_unused_used_templates(apps, schema_editor):
    Format = apps.get_model('VLE', 'Format')
    Template = apps.get_model('VLE', 'Template')
    for format in Format.objects.all():
        for template in format.unused_templates.all():
            template.preset_only = True
            template.format = format
            template.save()
        for template in format.available_templates.all():
            template.format = format
            template.save()
    for template in Template.objects.all():
        if template.format is None:
            if template.entry_set.count() > 0:
                template.format = template.entry_set.first().node.journal.assignment.format
                template.archived = True
                template.save()
            else:
                template.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0022_grade_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Format'),
        ),
        migrations.AddField(
            model_name='template',
            name='preset_only',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            update_unused_used_templates,
        ),
        migrations.RemoveField(
            model_name='format',
            name='available_templates',
        ),
        migrations.RemoveField(
            model_name='format',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='format',
            name='unused_templates',
        ),
        migrations.RemoveField(
            model_name='template',
            name='max_grade',
        ),
    ]
