# Generated by Django 2.1.7 on 2019-08-07 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0022_grade_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Format', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='preset_only',
            field=models.BooleanField(default=False),
        ),
    ]
