# Generated by Django 2.1.7 on 2019-08-07 14:28

from django.db import migrations


def update_unused_used_templates(apps, schema_editor):
    Format = apps.get_model('VLE', 'Format')
    Template = apps.get_model('VLE', 'Template')
    db_alias = schema_editor.connection.alias
    for format in Format.objects.all():
        for template in format.unused_templates.all():
            template.preset_only = True
            template.format = format
            template.save()
        for template in format.available_templates.all():
            template.format = format
            template.save()
    for template in Template.objects.using(db_alias).all():
        if template.format is None:
            if template.entry_set.count() > 0:
                template.format = template.entry_set.first().node.journal.assignment.format
                template.archived = True
                template.save()
    Template.objects.using(db_alias).filter(format__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0023_template_format_rework'),
    ]

    operations = [
        migrations.RunPython(
            update_unused_used_templates,
        ),
    ]
