# Generated by Django 2.1.7 on 2019-08-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0023_template_format_rework'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='grade_button_setting',
            field=models.TextField(choices=[('s', 's'), ('p', 'p')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='preferences',
            name='comment_button_setting',
            field=models.TextField(choices=[('s', 's'), ('p', 'p'), ('g', 'g')], default='s', max_length=2),
        ),
        migrations.AddField(
            model_name='preferences',
            name='auto_proceed_next_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferences',
            name='auto_select_ungraded_entry',
            field=models.BooleanField(default=True),
        ),
    ]
