# Generated by Django 2.1.7 on 2019-08-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0024_template_format_rework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='available_templates',
        ),
        migrations.RemoveField(
            model_name='format',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='format',
            name='unused_templates',
        ),
        migrations.RemoveField(
            model_name='template',
            name='max_grade',
        ),
        migrations.AlterField(
            model_name='template',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Format'),
        ),
    ]
