# Generated by Django 2.1.7 on 2019-09-15 08:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0028_lti_run'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lti_ids',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lti_ids',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='lti_ids',
            name='course',
        ),
        migrations.DeleteModel(
            name='Lti_ids',
        ),
    ]
