# Generated by Django 2.1.7 on 2019-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0030_datetime_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetnode',
            name='target',
            field=models.FloatField(null=True),
        ),
    ]
