# Generated by Django 2.2.6 on 2019-10-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0031_assignment_target_to_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='preset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VLE.PresetNode'),
        ),
    ]
