# Generated by Django 2.1.7 on 2019-04-28 15:51

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0033_sensible_lti_group_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='sourcedids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='journal',
            name='sourcedid',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='group_size',
            field=models.IntegerField(null=True, verbose_name='group_size'),
        ),
    ]
