# Generated by Django 2.1.7 on 2019-10-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0034_allow_same_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_test_student',
            field=models.BooleanField(default=False),
        ),
    ]
