# Generated by Django 2.1.7 on 2019-07-04 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0036_group_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcedid', models.TextField(null=True)),
                ('grade_url', models.TextField(null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Assignment')),
            ],
        ),
        migrations.RemoveField(
            model_name='journal',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='grade_url',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='sourcedids',
        ),
        migrations.AddField(
            model_name='assignmentparticipation',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='VLE.Journal'),
        ),
        migrations.AddField(
            model_name='assignmentparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentparticipation',
            unique_together={('assignment', 'user')},
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
