# Generated by Django 2.2.8 on 2019-12-17 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0036_mail_username_to_lower_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='can_lock_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='can_set_journal_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='can_set_journal_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_group_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='remove_grade_upon_leaving_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='author_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journal',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_journals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='journal',
            name='grade_url',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='sourcedid',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.CreateModel(
            name='AssignmentParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcedid', models.TextField(null=True)),
                ('grade_url', models.TextField(null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Assignment')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='VLE.Journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'user')},
            },
        ),
    ]
