# Generated by Django 2.2.6 on 2019-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0037_group_assignments2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='group_size',
        ),
        migrations.AddField(
            model_name='assignment',
            name='can_lock_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='can_set_journal_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='can_set_journal_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_group_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
