# Generated by Django 2.2.8 on 2020-01-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0037_group_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='LMS_grade',
            field=models.IntegerField(default=0),
        ),
    ]
