# Generated by Django 2.2.8 on 2019-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0037_group_assignments2'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_edit_journals',
            field=models.BooleanField(default=False),
        ),
    ]
