# Generated by Django 2.2.8 on 2020-02-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0038_file_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='hide_version_alert',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
