all:
  children:
    staging:
      vars:
        env: stage
      hosts:
        test.ejournal.app:
          baselink: https://test.ejournal.app
          api_url: https://api.test.ejournal.app
          mailgun_sender_domain: test.ejournal.app
    production:
      vars:
        env: production
      hosts:
        uva.ejournal.app:
          baselink: https://uva.ejournal.app
          api_url: https://api.uva.ejournal.app
          mailgun_sender_domain: uva.ejournal.app
