---

- include: copy_scripts.yml
  tags: celery

- include: setup_celery_supervisor_logs.yml
  tags: celery

- include: setup_celery_supervisor.yml
  tags: celery

- include: restart_celery.yml
  tags:
    - never
    - deploy_back
