---

- name: Restart {{ celery_application_name }}_beat
  supervisorctl:
    name: "{{ celery_application_name }}_beat"
    state: restarted

- name: Restart {{ celery_application_name }}_worker
  supervisorctl:
    name: "{{ celery_application_name }}_worker"
    state: restarted
    
