route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        text: "{%raw%}{{ .CommonAnnotations.description }}{%endraw%}"
        username: "Prometheus"
        channel: "#monitoring"
        api_url: "{{ slack_notifications_incoming_webhook }}"
