const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const FORBIDDEN = 403
const NOT_FOUND = 404
const INTERNAL_SERVER_ERROR = 500

export default {
    BAD_REQUEST: BAD_REQUEST,
    UNAUTHORIZED: UNAUTHORIZED,
    FORBIDDEN: FORBIDDEN,
    NOT_FOUND: NOT_FOUND,
    INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR
}
