---

- name: Create the folder for the celery scripts
  file: path={{ celery_scripts_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        mode=0774
        state=directory

- name: Create the {{ celery_application_name }} worker start script file
  template: src={{ celery_worker_start_template_file }}
            dest={{ celery_scripts_dir }}/{{ celery_application_name }}_worker_start
            owner={{ celery_user }}
            group={{ celery_group }}
            mode=0755

- name: Create the {{ celery_application_name }} beat start script file
  template: src={{ celery_beat_start_template_file }}
            dest={{ celery_scripts_dir }}/{{ celery_application_name }}_beat_start
            owner={{ celery_user }}
            group={{ celery_group }}
            mode=0755
