# Generated by Django 2.0.6 on 2018-06-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('late', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('AD', 'Admin'), ('TE', 'Teacher'), ('TA', 'Teacher assistant'), ('SU', 'Student')], default='SU', max_length=2)),
                ('email', models.TextField(null=True, unique=True)),
                ('username', models.TextField(unique=True)),
                ('passhash', models.CharField(max_length=256)),
                ('education', models.TextField(null=True)),
                ('lti_id', models.TextField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'education')},
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.User'),
        ),
        migrations.AddField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Journal'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ManyToManyField(to='VLE.User'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ManyToManyField(to='VLE.Course'),
        ),
    ]
