<!-- TODO Is this check really required if we redirect, or even better have correct flow anyway? -->
<template v-if="$hasPermission('can_view_all_journals')">
    <content-columns>
        <bread-crumb
            slot="main-content-column"
            @edit-click="handleEdit()"
        />

        <div slot="main-content-column">
            <input
                v-model="searchValue"
                class="theme-input full-width multi-form"
                type="text"
                placeholder="Search..."
            />

            <div class="d-flex">
                <b-form-select
                    v-if="groups.length > 0"
                    v-model="journalGroupFilter"
                    :selectSize="1"
                    class="multi-form mr-2"
                >
                    <option :value="null">
                        Filter on group...
                    </option>
                    <option
                        v-for="group in groups"
                        :key="group.name"
                        :value="group.name"
                    >
                        {{ group.name }}
                    </option>
                </b-form-select>
                <b-form-select
                    v-model="selectedSortOption"
                    :selectSize="1"
                    class="multi-form mr-2"
                >
                    <option value="name">
                        Sort by name
                    </option>
                    <option value="username">
                        Sort by username
                    </option>
                    <option value="markingNeeded">
                        Sort by marking needed
                    </option>
                    <option value="points">
                        Sort by points
                    </option>
                </b-form-select>
                <b-button
                    v-if="!order"
                    class="multi-form"
                    @click.stop
                    @click="toggleOrder(!order)"
                >
                    <icon name="long-arrow-down"/>
                    Ascending
                </b-button>
                <b-button
                    v-if="order"
                    class="multi-form"
                    @click.stop
                    @click="toggleOrder(!order)"
                >
                    <icon name="long-arrow-up"/>
                    Descending
                </b-button>
            </div>

            <div class="d-flex flex-wrap">
                <b-button
                    v-if="$hasPermission('can_publish_grades') && assignmentJournals.length > 0"
                    class="add-button multi-form fill-form-width"
                    @click="publishGradesAssignment"
                >
                    <icon name="upload"/>
                    Publish all Grades for this Assignment
                </b-button>
                <b-button
                    v-if="$hasPermission('can_publish_grades') && assignmentJournals.length > 0"
                    class="change-button multi-form flex-grow-1"
                    @click="showModal('bonusPointsModal')"
                >
                    <icon name="star"/>
                    Import bonus points
                </b-button>
            </div>

            <b-modal
                ref="bonusPointsModal"
                title="Import bonus points"
                size="lg"
                hideFooter
                @hide="$refs['bounsPointsUpload'].resetErrorLogs()"
            >
                <b-card class="no-hover">
                    <h2>Add bonus points to multiple journals at once</h2>
                    Use the button below to import bonus points from a <i>comma separated value</i> file (.csv).
                    This type of file can be easily generated by any spreadsheet application. Use the following
                    format:<br/>

                    <div class="text-monospace multi-form full-width text-center">
                        username1, bonus1<br/>
                        username2, bonus2<br/>
                        username3, bonus3<br/>
                    </div>

                    <b>Note:</b> Importing bonus points for a user will overwrite their current bonus points!

                    <bonus-file-upload-input
                        ref="bounsPointsUpload"
                        :acceptedFiletype="'*/*.csv'"
                        :maxSizeBytes="$root.maxFileSizeBytes"
                        :endpoint="'assignments/' + $route.params.aID + '/add_bonus_points'"
                        :aID="$route.params.aID"
                        class="mt-2"
                        @bonusPointsSuccesfullyUpdated="hideModal('bonusPointsModal'); init()"
                    />
                </b-card>
            </b-modal>
        </div>

        <div
            v-for="journal in filteredJournals"
            slot="main-content-column"
            :key="journal.students[0].id"
        >
            <b-link
                :to="{
                    name: 'Journal',
                    params: {
                        cID: cID,
                        aID: aID,
                        jID: journal.id
                    }
                }"
                tag="b-button"
            >
                <student-card
                    :listView="true"
                    :journal="journal"
                />
            </b-link>
        </div>

        <main-card
            v-if="loadingJournals && assignmentJournals.length === 0"
            slot="main-content-column"
            :line1="'Loading journals...'"
            class="no-hover"
        />
        <main-card
            v-else-if="assignmentJournals.length === 0"
            slot="main-content-column"
            :line1="'No participants with a journal'"
            class="no-hover"
        />
        <main-card
            v-else-if="filteredJournals.length === 0"
            slot="main-content-column"
            :line1="'No journals found'"
            class="no-hover"
        />

        <div
            v-if="stats"
            slot="right-content-column"
        >
            <h3>Insights</h3>
            <statistics-card :stats="stats"/>
        </div>
    </content-columns>
</template>

<script>
import contentColumns from '@/components/columns/ContentColumns.vue'
import studentCard from '@/components/assignment/StudentCard.vue'
import mainCard from '@/components/assets/MainCard.vue'
import statisticsCard from '@/components/assignment/StatisticsCard.vue'
import breadCrumb from '@/components/assets/BreadCrumb.vue'
import bonusFileUploadInput from '@/components/assets/file_handling/BonusFileUploadInput.vue'

import store from '@/Store.vue'
import assignmentAPI from '@/api/assignment.js'
import groupAPI from '@/api/group.js'
import participationAPI from '@/api/participation.js'
import { mapGetters, mapMutations } from 'vuex'

export default {
    name: 'Assignment',
    components: {
        contentColumns,
        studentCard,
        statisticsCard,
        breadCrumb,
        bonusFileUploadInput,
        mainCard,
    },
    props: {
        cID: {
            required: true,
        },
        aID: {
            required: true,
        },
    },
    data () {
        return {
            assignmentJournals: [],
            stats: null,
            groups: [],
            loadingJournals: true,
        }
    },
    computed: {
        ...mapGetters({
            journalSortBy: 'preferences/journalSortBy',
            order: 'preferences/journalSortAscending',
            getJournalSearchValue: 'preferences/journalSearchValue',
            getJournalGroupFilter: 'preferences/journalGroupFilter',
            getSelfSetGroupFilter: 'preferences/journalSelfSetGroupFilter',
        }),
        journalGroupFilter: {
            get () {
                return this.getJournalGroupFilter
            },
            set (value) {
                this.setJournalGroupFilter(value)
                this.setSelfSetGroupFilter(true)
            },
        },
        searchValue: {
            get () {
                return this.getJournalSearchValue
            },
            set (value) {
                this.setJournalSearchValue(value)
            },
        },
        selectedSortOption: {
            get () {
                return this.journalSortBy
            },
            set (value) {
                this.setJournalSortBy(value)
            },
        },
        filteredJournals () {
            const self = this

            function compareFullName (a, b) {
                return self.compare(a.students[0].full_name, b.students[0].full_name)
            }

            function compareUsername (a, b) {
                return self.compare(a.students[0].username, b.students[0].username)
            }

            function compareMarkingNeeded (a, b) {
                return self.compare(a.stats.submitted - a.stats.graded, b.stats.submitted - b.stats.graded)
            }

            function comparePoints (a, b) {
                return self.compare(a.stats.acquired_points, b.stats.acquired_points)
            }

            function searchFilter (journal) {
                const username = journal.students.map(s => s.username).toString().toLowerCase()
                const fullname = journal.students.map(s => s.full_name).toString().toLowerCase()
                const searchValue = self.searchValue.toLowerCase()

                return username.includes(searchValue)
                    || fullname.includes(searchValue)
            }

            function groupFilter (journal) {
                if (self.getJournalGroupFilter) {
                    return journal.students.map(s => s.groups.map(g => g.name)).flat(1)
                        .includes(self.getJournalGroupFilter)
                }

                return true
            }

            /* Filter list based on search input. */
            if (this.selectedSortOption === 'name') {
                store.setFilteredJournals(this.assignmentJournals.filter(searchFilter).sort(compareFullName))
            } else if (this.selectedSortOption === 'username') {
                store.setFilteredJournals(this.assignmentJournals.filter(searchFilter).sort(compareUsername))
            } else if (this.selectedSortOption === 'markingNeeded') {
                store.setFilteredJournals(this.assignmentJournals.filter(searchFilter).sort(compareMarkingNeeded))
            } else if (this.selectedSortOption === 'points') {
                store.setFilteredJournals(this.assignmentJournals.filter(searchFilter).sort(comparePoints))
            }

            this.calcStats(store.state.filteredJournals.filter(groupFilter))

            return store.state.filteredJournals.filter(groupFilter).slice()
        },
    },
    created () {
        // TODO Should be moved to the breadcrumb, ensuring there is no more natural flow left that can get you to this
        // page without manipulating the url manually. If someone does this, simply let the error be thrown
        // (no checks required)
        if (!this.$hasPermission('can_view_all_journals', 'assignment', String(this.aID))) {
            if (this.$root.previousPage) {
                this.$router.push({ name: this.$root.previousPage.name, params: this.$root.previousPage.params })
            } else {
                this.$router.push({ name: 'Home' })
            }
            return
        }

        this.init()
    },
    methods: {
        ...mapMutations({
            setJournalSortBy: 'preferences/SET_JOURNAL_SORT_BY',
            toggleOrder: 'preferences/SET_JOURNAL_SORT_ASCENDING',
            setJournalSearchValue: 'preferences/SET_JOURNAL_SEARCH_VALUE',
            setJournalGroupFilter: 'preferences/SET_JOURNAL_GROUP_FILTER',
            switchJournalAssignment: 'preferences/SWITCH_JOURNAL_ASSIGNMENT',
            setSelfSetGroupFilter: 'preferences/SET_JOURNAL_SELF_SET_GROUP_FILTER',
        }),
        init () {
            this.switchJournalAssignment(this.aID)

            const initialCalls = []
            initialCalls.push(assignmentAPI.get(this.aID, this.cID))
            initialCalls.push(groupAPI.getAllFromCourse(this.cID))
            initialCalls.push(participationAPI.get(this.cID))

            Promise.all(initialCalls).then((results) => {
                this.loadingJournals = false
                this.assignmentJournals = results[0].journals
                this.groups = results[1].sort((a, b) => b.name < a.name)
                const participant = results[2]

                /* If there are no groups or the current group filter yields no journals, remove the filter. */
                if (!this.groups || !this.groups.some(group => group.name === this.getJournalGroupFilter)) {
                    this.setJournalGroupFilter(null)
                }

                /* If the group filter has not been set, set it to the
                   group of the user provided that yields journals. */
                if (!this.getSelfSetGroupFilter && participant && participant.groups) {
                    participant.groups.forEach((group) => {
                        this.setJournalGroupFilter(group.name)
                        if (!this.filteredJournals.length) {
                            this.setJournalGroupFilter(null)
                        } else {
                            return /* eslint no-useless-return: "off" */
                        }
                    })
                }
            })
        },
        showModal (ref) {
            this.$refs[ref].show()
        },
        hideModal (ref) {
            this.$refs[ref].hide()
        },
        handleEdit () {
            this.$router.push({
                name: 'FormatEdit',
                params: {
                    cID: this.cID,
                    aID: this.aID,
                },
            })
        },
        publishGradesAssignment () {
            if (window.confirm('Are you sure you want to publish all grades for each journal?')) {
                assignmentAPI.update(this.aID, { published: true }, {
                    customErrorToast: 'Error while publishing all grades for this assignment.',
                    customSuccessToast: 'Published all grades for this assignment.',
                })
                    .then(() => {
                        assignmentAPI.get(this.aID, this.cID)
                            .then((assignment) => {
                                this.assignmentJournals = assignment.journals
                                this.stats = assignment.stats
                            })
                    })
            }
        },
        compare (a, b) {
            if (a < b) { return this.order ? 1 : -1 }
            if (a > b) { return this.order ? -1 : 1 }
            return 0
        },
        calcStats (filteredJournals) {
            let needsMarking = 0
            let unpublished = 0
            let points = 0

            for (let i = 0; i < filteredJournals.length; i++) {
                needsMarking += filteredJournals[i].stats.submitted - filteredJournals[i].stats.graded
                unpublished += filteredJournals[i].stats.submitted - filteredJournals[i].stats.published
                points += filteredJournals[i].stats.acquired_points
            }
            this.stats = {}
            this.stats.needsMarking = needsMarking
            this.stats.unpublished = unpublished - needsMarking
            this.stats.averagePoints = points / filteredJournals.length
        },
    },
}
</script>
