<!-- TODO Is this check really required if we redirect, or even better have correct flow anyway? -->
<template v-if="$hasPermission('can_view_all_journals')">
    <content-columns>
        <bread-crumb
            slot="main-content-column"
            @edit-click="handleEdit()"
        />

        <div slot="main-content-column">
            <input
                v-model="searchValue"
                class="theme-input full-width multi-form"
                type="text"
                placeholder="Search..."
            />

            <div class="d-flex">
                <theme-select
                    v-model="journalGroupFilter"
                    label="name"
                    trackBy="name"
                    :options="groups"
                    :multiple="true"
                    :searchable="true"
                    :multiSelectText="`active group filter${journalGroupFilter &&
                        journalGroupFilter.length === 1 ? '' : 's'}`"
                    placeholder="Filter by group"
                    class="multi-form mr-2"
                />
                <b-form-select
                    v-model="selectedSortOption"
                    :selectSize="1"
                    class="multi-form mr-2"
                >
                    <option value="name">
                        Sort by name
                    </option>
                    <option value="username">
                        Sort by username
                    </option>
                    <option value="markingNeeded">
                        Sort by marking needed
                    </option>
                    <option value="points">
                        Sort by points
                    </option>
                </b-form-select>
                <b-button
                    v-if="!order"
                    class="multi-form"
                    @click.stop
                    @click="toggleOrder(!order)"
                >
                    <icon name="long-arrow-down"/>
                    Ascending
                </b-button>
                <b-button
                    v-if="order"
                    class="multi-form"
                    @click.stop
                    @click="toggleOrder(!order)"
                >
                    <icon name="long-arrow-up"/>
                    Descending
                </b-button>
            </div>

            <div class="d-flex flex-wrap">
                <b-button
                    v-if="$hasPermission('can_publish_grades') && assignmentJournals && assignmentJournals.length > 0"
                    class="add-button multi-form fill-form-width"
                    @click="publishGradesAssignment"
                >
                    <icon name="upload"/>
                    {{ assignment.journals.length === filteredJournals.length ?
                        "Publish all grades" : "Publish grades" }}
                </b-button>
                <b-button
                    v-if="$hasPermission('can_edit_assignment') && assignment.lti_courses
                        && Object.keys(assignment.lti_courses).length > 1"
                    class="add-button multi-form fill-form-width"
                    @click="showModal('manageLTIModal')"
                >
                    <icon name="graduation-cap"/>
                    Manage LTI
                </b-button>
                <b-button
                    v-if="$hasPermission('can_publish_grades') && assignmentJournals.length > 0"
                    class="change-button multi-form flex-grow-1"
                    @click="showModal('bonusPointsModal')"
                >
                    <icon name="star"/>
                    Import bonus points
                </b-button>
            </div>

            <b-modal
                ref="bonusPointsModal"
                title="Import bonus points"
                size="lg"
                hideFooter
                @hide="$refs['bounsPointsUpload'].resetErrorLogs()"
            >
                <b-card class="no-hover">
                    <h2 class="theme-h2">Add bonus points to multiple journals at once</h2><hr/>
                    Use the button below to import bonus points from a <i>comma separated value</i> file (.csv).
                    This type of file can be easily generated by any spreadsheet application. Use the following
                    format:<br/>

                    <div class="text-monospace multi-form full-width text-center">
                        username1, bonus1<br/>
                        username2, bonus2<br/>
                        username3, bonus3<br/>
                    </div>

                    <b>Note:</b> Importing bonus points for a user will overwrite their current bonus points!

                    <bonus-file-upload-input
                        ref="bounsPointsUpload"
                        :acceptedFiletype="'*/*.csv'"
                        :maxSizeBytes="$root.maxFileSizeBytes"
                        :endpoint="'assignments/' + $route.params.aID + '/add_bonus_points'"
                        :aID="$route.params.aID"
                        class="mt-2"
                        @bonusPointsSuccesfullyUpdated="hideModal('bonusPointsModal'); init()"
                    />
                </b-card>
            </b-modal>

            <b-modal
                v-if="$hasPermission('can_edit_assignment') && assignment.lti_courses
                    && Object.keys(assignment.lti_courses).length > 1"
                ref="manageLTIModal"
                title="Manage LTI"
                size="lg"
                hideFooter
                @show="newActiveLTICourse = assignment.active_lti_course.cID"
                @hide="newActiveLTICourse = null"
            >
                <b-card class="no-hover">
                    <h2 class="theme-h2">Select active course</h2><hr/>
                    This assignment is linked to multiple courses on your LMS.
                    Grades can only be passed back to one course at a time.
                    Select from the options below which course should be used for grade passback.<br/>

                    <b-form-select
                        v-model="newActiveLTICourse"
                        class="full-width mt-2 mb-2"
                    >
                        <option
                            v-for="(name, id) in assignment.lti_courses"
                            :key="`lti-option-${cID}-${id}`"
                            :value="parseInt(id)"
                        >
                            {{ name }}
                        </option>
                    </b-form-select>

                    <b class="text-red">Warning:</b> After changing this option, students will not be
                    able to update their journals for this assignment until they visit the assignment
                    on your LMS at least once.<br/>

                    <b-button
                        class="add-button d-block float-right"
                        :class="{'input-disabled': assignment.active_lti_course.cID === newActiveLTICourse}"
                        @click="saveNewActiveLTICourse"
                    >
                        <icon name="save"/>
                        Save
                    </b-button>
                </b-card>
            </b-modal>
        </div>

        <load-wrapper
            slot="main-content-column"
            :loading="loadingJournals"
        >
            <div
                v-for="journal in filteredJournals"
                :key="journal.student.id"
            >
                <b-link
                    :to="{
                        name: 'Journal',
                        params: {
                            cID: cID,
                            aID: aID,
                            jID: journal.id
                        }
                    }"
                    tag="b-button"
                >
                    <student-card
                        :listView="true"
                        :student="journal.student"
                        :stats="journal.stats"
                        :assignment="assignment"
                    />
                </b-link>
            </div>
            <main-card
                v-if="assignmentJournals.length === 0"
                line1="No participants with a journal"
                line2="There are no journals for this assignment."
                class="no-hover border-dark-grey"
            />
            <main-card
                v-else-if="filteredJournals.length === 0"
                line1="No journals found"
                line2="There are no journals that match your search query."
                class="no-hover border-dark-grey"
            />
        </load-wrapper>

        <div
            v-if="stats"
            slot="right-content-column"
        >
            <h3 class="theme-h3">Insights</h3>
            <statistics-card :stats="stats"/>
        </div>
    </content-columns>
</template>

<script>
import bonusFileUploadInput from '@/components/assets/file_handling/BonusFileUploadInput.vue'
import breadCrumb from '@/components/assets/BreadCrumb.vue'
import contentColumns from '@/components/columns/ContentColumns.vue'
import loadWrapper from '@/components/loading/LoadWrapper.vue'
import mainCard from '@/components/assets/MainCard.vue'
import statisticsCard from '@/components/assignment/StatisticsCard.vue'
import studentCard from '@/components/assignment/StudentCard.vue'

import store from '@/Store.vue'
import assignmentAPI from '@/api/assignment.js'
import groupAPI from '@/api/group.js'
import gradeAPI from '@/api/grade.js'
import participationAPI from '@/api/participation.js'
import journalAPI from '@/api/journal.js'
import { mapGetters, mapMutations } from 'vuex'

export default {
    name: 'Assignment',
    components: {
        bonusFileUploadInput,
        breadCrumb,
        contentColumns,
        loadWrapper,
        mainCard,
        statisticsCard,
        studentCard,
    },
    props: {
        cID: {
            required: true,
        },
        aID: {
            required: true,
        },
    },
    data () {
        return {
            assignment: {},
            assignmentJournals: [],
            stats: null,
            groups: [],
            loadingJournals: true,
            newActiveLTICourse: null,
            filteredGroups: null,
        }
    },
    computed: {
        ...mapGetters({
            journalSortBy: 'preferences/journalSortBy',
            isSuperuser: 'user/isSuperuser',
            order: 'preferences/journalSortAscending',
            getJournalSearchValue: 'preferences/journalSearchValue',
            getJournalGroupFilter: 'preferences/journalGroupFilter',
            getSelfSetGroupFilter: 'preferences/journalSelfSetGroupFilter',
        }),
        journalGroupFilter: {
            get () {
                return this.getJournalGroupFilter
            },
            set (value) {
                this.setJournalGroupFilter(value)
                this.setSelfSetGroupFilter(true)
            },
        },
        searchValue: {
            get () {
                return this.getJournalSearchValue
            },
            set (value) {
                this.setJournalSearchValue(value)
            },
        },
        selectedSortOption: {
            get () {
                return this.journalSortBy
            },
            set (value) {
                this.setJournalSortBy(value)
            },
        },
        filteredJournals () {
            store.setFilteredJournals(this.assignmentJournals, this.order, this.journalGroupFilter,
                this.getJournalSearchValue, this.journalSortBy)
            this.calcStats(store.state.filteredJournals)
            return store.state.filteredJournals
        },
    },
    created () {
        // TODO Should be moved to the breadcrumb, ensuring there is no more natural flow left that can get you to this
        // page without manipulating the url manually. If someone does this, simply let the error be thrown
        // (no checks required)
        if (!this.$hasPermission('can_view_all_journals', 'assignment', String(this.aID))) {
            if (this.$root.previousPage) {
                this.$router.push({ name: this.$root.previousPage.name, params: this.$root.previousPage.params })
            } else {
                this.$router.push({ name: 'Home' })
            }
            return
        }

        this.init()
    },
    methods: {
        ...mapMutations({
            setJournalSortBy: 'preferences/SET_JOURNAL_SORT_BY',
            toggleOrder: 'preferences/SET_JOURNAL_SORT_ASCENDING',
            setJournalSearchValue: 'preferences/SET_JOURNAL_SEARCH_VALUE',
            setJournalGroupFilter: 'preferences/SET_JOURNAL_GROUP_FILTER',
            switchJournalAssignment: 'preferences/SWITCH_JOURNAL_ASSIGNMENT',
            setSelfSetGroupFilter: 'preferences/SET_JOURNAL_SELF_SET_GROUP_FILTER',
        }),
        init () {
            this.switchJournalAssignment(this.aID)

            const initialCalls = []
            initialCalls.push(assignmentAPI.get(this.aID, this.cID))
            initialCalls.push(groupAPI.getAllFromCourse(this.cID))
            /* Superuser does not have any participation, this should not redict to error, nor give an error toast */
            initialCalls.push(
                participationAPI.get(this.cID, { redirect: !this.isSuperuser, customErrorToast: '' }).catch(() => {}))

            Promise.all(initialCalls).then((results) => {
                this.loadingJournals = false
                this.assignment = results[0]
                this.assignmentJournals = results[0].journals
                this.groups = results[1].sort((a, b) => b.name < a.name)
                const participant = results[2]

                /* If the group filter has not been set, set it to the
                   group of the user provided that yields journals. */
                if (!this.getSelfSetGroupFilter && participant && participant.groups) {
                    this.setJournalGroupFilter(participant.groups)
                }

                /* If there are no groups or the current group filter yields no journals, remove the filter. */
                if (!this.groups || this.filteredJournals.length === 0) {
                    this.setJournalGroupFilter(null)
                }
            })
        },
        showModal (ref) {
            this.$refs[ref].show()
        },
        hideModal (ref) {
            this.$refs[ref].hide()
        },
        handleEdit () {
            this.$router.push({
                name: 'FormatEdit',
                params: {
                    cID: this.cID,
                    aID: this.aID,
                },
            })
        },
        publishGradesAssignment () {
            if (this.assignment.journals.length === store.state.filteredJournals.length) {
                if (window.confirm('Are you sure you want to publish the grades for all journals?')) {
                    gradeAPI.publish_all_assignment_grades(this.aID, {
                        customErrorToast: 'Error while publishing all grades for this assignment.',
                        customSuccessToast: 'Published all grades for this assignment.',
                    }).then(() => {
                        assignmentAPI.get(this.aID, this.cID)
                            .then((assignment) => {
                                this.assignmentJournals = assignment.journals
                                this.stats = assignment.stats
                            })
                    })
                }
            } else if (window.confirm('Are you sure you want to publish the grades of the filtered journals?')) {
                const allJournals = []
                this.filteredJournals.forEach((journal) => {
                    allJournals.push(journalAPI.update(journal.id, { published: true }, {
                        customErrorToast: `Error while publishing grades for ${journal.student}.`,
                    }))
                })
                Promise.all(allJournals).then(() => {
                    this.$toasted.success('Published grades.')
                    assignmentAPI.get(this.aID, this.cID)
                        .then((assignment) => {
                            this.assignmentJournals = assignment.journals
                            this.stats = assignment.stats
                        })
                })
            }
        },
        saveNewActiveLTICourse () {
            if (window.confirm('Are you sure you want to change the active LTI course for grade passback?'
                + ' Students will not be able to update their journals for this assignment until they visit'
                + ' the assignment on your LMS at least once.')) {
                assignmentAPI.update(this.aID, {
                    active_lti_course: this.newActiveLTICourse,
                })
                    .then(() => {
                        this.$toasted.success('Updated active LTI course')
                        this.$refs.manageLTIModal.hide()
                    })
            }
        },
        calcStats (filteredJournals) {
            let needsMarking = 0
            let unpublished = 0
            let points = 0

            for (let i = 0; i < filteredJournals.length; i++) {
                needsMarking += filteredJournals[i].stats.submitted - filteredJournals[i].stats.graded
                unpublished += filteredJournals[i].stats.submitted - filteredJournals[i].stats.published
                points += filteredJournals[i].stats.acquired_points
            }
            this.stats = {}
            this.stats.needsMarking = needsMarking
            this.stats.unpublished = unpublished - needsMarking
            this.stats.averagePoints = points / filteredJournals.length
        },
    },
}
</script>
