all:
  children:
    staging:
      vars:
        env: stage
        server_user: mel
      hosts:
        test.ejournal.app:
          baselink: https://test.ejournal.app
          api_url: https://api.test.ejournal.app
          mailgun_sender_domain: test.ejournal.app
    production:
      vars:
        env: production
        server_user: root
      hosts:
        uva.ejournal.app:
          baselink: https://uva.ejournal.app
          api_url: https://api.uva.ejournal.app
          mailgun_sender_domain: uva.ejournal.app
    test:
      vars:
        env: stage
        server_user: ubuntu
      hosts:
        test.ejournal.app:
          baselink: https://test.ejournal.app
          api_url: https://api.test.ejournal.app
          mailgun_sender_domain: test.ejournal.app
    pr:
      vars:
        env: stage
        server_user: ubuntu
      hosts:
        pr.ejournal.app:
          baselink: https://pr.ejournal.app
          api_url: https://api.pr.ejournal.app
          mailgun_sender_domain: pr.ejournal.app