all:
  children:
    staging:
      vars:
        env: stage
      hosts:
        devops2.ejournal.app:
          baselink: https://ec2-3-87-161-173.compute-1.amazonaws.com
          api_url: https://api.ec2-3-87-161-173.compute-1.amazonaws.com
          mailgun_sender_domain: ec2-3-87-161-173.compute-1.amazonaws.com
    # production:
    #   vars:
    #     env: production
    #   hosts:
    #     uva.ejournal.app:
    #       baselink: https://uva.ejournal.app
    #       api_url: https://api.uva.ejournal.app
    #       mailgun_sender_domain: uva.ejournal.app
