all:
  children:
    staging:
      vars:
        env: stage
        server_user: mel
      hosts:
        test.ejournal.app:
          baselink: https://test.ejournal.app
          api_url: https://api.test.ejournal.app
          mailgun_sender_domain: test.ejournal.app
    production:
      vars:
        env: production
        server_user: root
      hosts:
        uva.ejournal.app:
          baselink: https://uva.ejournal.app
          api_url: https://api.uva.ejournal.app
          mailgun_sender_domain: uva.ejournal.app
    demo:
      vars:
        env: stage
        server_user: ubuntu
      hosts:
        demo.ejournal.app:
          baselink: https://demo.ejournal.app
          api_url: https://api.demo.ejournal.app
          mailgun_sender_domain: demo.ejournal.app
    webhook:
      vars:
        env: stage
        server_user: ubuntu
      hosts:
        demo.ejournal.app:
          baselink: http://webhook.ejournal.app/
    webhook-test:
      vars:
        env: stage
        server_user: ubuntu
      hosts:
        ec2-54-225-11-171.compute-1.amazonaws.com:
          baselink: http://ec2-54-225-11-171.compute-1.amazonaws.com
