---

- name: Provision the {{ application_name }} web server
  hosts: pr
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - db
    - certbot
    - rabbitmq
    - web
    - celery
    - nginx
    - security
