---

- name: Check for an existing db-backup directory
  stat:
    path: "{{ db_backup_dir }}"
  register: dbbdir

- name: Ensures the backup directory exists
  file:
    path: "{{ db_backup_dir }}"
    owner: postgres
    group: postgres
    mode: 0775
    state: directory
  when: not dbbdir.stat.exists or not dbbdir.stat.isdir

- name: Dump db {{ db_name }} to {{ db_backup_dir }}/
  postgresql_db:
    name: "{{ db_name }}"
    state: dump
    target: "{{ db_backup_dir }}/{{ application_name }}-{{ ansible_date_time.epoch }}.sql.gz"
  become: yes
  become_user: postgres

- name: Copy the database dump to the local machine
  fetch:
    src: "{{ db_backup_dir }}/{{ application_name }}-{{ ansible_date_time.epoch }}.sql.gz"
    dest: "{{ local_backup_dir }}/"
    flat: yes
