all:
  children:
    monitoring:
      vars:
        ansible_ssh_private_key_file: <path_to_key>
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_user: <ssh_user>
      hosts:
        sentry.ejournal.app:
