"""
Django settings for VLE project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

# SECURITY WARNING: KEEP secret
SECRET_KEY = '{{SECRET_KEY}}'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ejourn.al.trial@gmail.com'
EMAIL_HOST_PASSWORD = 'M@@rten1523'
EMAIL_PORT = 587

from VLE.settings.base import *

# SECURITY WARNING: KEEP secret
LTI_SECRET = '{{LTI_SECRET}}'
LTI_KEY = '{{LTI_KEY}}'

USER_MAX_FILE_SIZE_BYTES = 2 * 1024 * 1024
USER_MAX_TOTAL_STORAGE_BYTES = 100 * 1024 * 1024

BASELINK = '{{BASELINK}}'
CORS_ORIGIN_ALLOW_ALL = True

USER_MAX_FILE_SIZE_BYTES = '{{USER_MAX_FILE_SIZE_BYTES}}'
USER_MAX_TOTAL_STORAGE_BYTES = '{{USER_MAX_TOTAL_STORAGE_BYTES}}'

MIDDLEWARE = ['corsheaders.middleware.CorsMiddleware'] + MIDDLEWARE
ALLOWED_HOSTS = ['*']

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.{{DATABASE_TYPE}}',
        'NAME': '{{DATABASE_NAME}}',
        'USER': '{{DATABASE_USER}}',
        'PASSWORD': '{{DATABASE_PASSWORD}}',
        'HOST': '{{DATABASE_HOST}}',
        'PORT': '{{DATABASE_PORT}}',
    }
}
