---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure aptitude is present for upgrades
  apt:
    update_cache: "{{ update_apt_cache }}"
    pkg: aptitude
    state: present

- name: Install security updates
  apt: default_release={{ ansible_distribution_release }}-security
       update_cache={{ update_apt_cache }}
       upgrade=dist
  tags:
    - packages
    - skip_ansible_lint
  when: ansible_distribution == 'Ubuntu'

- include: debian_apt.yml
  when: ansible_distribution == 'Debian'
  tags:
    - packages
    - packages.security

- name: Install base packages
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
      - locales
      - build-essential
      - acl
      - ntp
      - htop
      - git
      - "{{ base_python_package }}-pip"
      - "i{{ base_python_package }}"
      - supervisor
      - apt-transport-https
      - dirmngr
  tags:
    - packages
    - packages.security

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
    - skip_ansible_lint
